BikeStoreSampleMvcEFCore.Web/Models/Pager.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BikeStoreSampleMvcEFCore.Web.Models
{
    public class Pager
    {
        public int TotalItems { get; private set; }
        public int CurrentPage { get; private set; }
        public int PageSize { get; private set; }

        public int TotalPages { get; private set; }
        public int StartPage { get; private set; }
        public int EndPage { get; private set; }

        public Pager()
        {

        }

        public Pager(int totalItems, int page, int pageSize=10)
        {
            int totalPages = (int)Math.Ceiling((decimal)totalItems / (decimal)pageSize);
            int currentPage = page;

            int startPage = currentPage - 5;
            int endPage = currentPage + 4;

            if (startPage <= 0)
            {
                endPage = endPage - (startPage - 1);
                startPage = 1;
            }

            if (endPage > totalPages)
            {
                endPage = totalPages;
                if (endPage > 10)
                {
                    startPage = endPage - 9;
                }
            }

            TotalItems = totalItems;
            CurrentPage = currentPage;
            PageSize = pageSize;
            TotalPages = totalPages;
            StartPage = startPage;
            EndPage = endPage;


          }


    }
}

BikeStoreSampleMvcEFCore.Web/Controllers/CustomerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using BikeStoreSampleMvcEFCore.Web.Data;
using BikeStoreSampleMvcEFCore.Web.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace BikeStoreSampleMvcEFCore.Web.Controllers
{
    public class CustomerController : Controller
    {
        private readonly BikeContext _context;

        public CustomerController(BikeContext context)
        {
            _context = context;
        }

        public IActionResult Index(int pg = 1)
        {
            const int pageSize = 10;

            if (pg < 1)
                pg = 1;

            int recsCount = _context.Customers.Count();

            var pager = new Pager(recsCount, pg, pageSize);

            int recSkip = (pg - 1) * pageSize;

            List<Customer> customers = _context.Customers.OrderByDescending(x => x.CustomerId).Skip(recSkip).Take(pager.PageSize).ToList();

            this.ViewBag.Pager = pager;

            return View(customers);
        }

        public IActionResult Details(int Id)
        {
            Customer customer = _context.Customers.Where(x => x.CustomerId == Id).FirstOrDefault();
            return View(customer);
        }

        [HttpGet]
        public IActionResult Edit(int Id)
        {
            Customer customer = _context.Customers.Where(x => x.CustomerId == Id).First();
            return View(customer);
        }

        [HttpPost]
        public IActionResult Edit(Customer customer)
        {
            _context.Attach(customer);
            _context.Entry(customer).State = EntityState.Modified;
            _context.SaveChanges();
            return RedirectToAction("index");
        }

        [HttpGet]
        public IActionResult Delete(int Id)
        {
            Customer customer = _context.Customers.Where(x => x.CustomerId == Id).FirstOrDefault();
            return View(customer);
        }

        [HttpPost]
        public IActionResult Delete(Customer customer)
        {
            _context.Attach(customer);
            _context.Entry(customer).State = EntityState.Deleted;
            _context.SaveChanges();
            return RedirectToAction("index");
        }

        [HttpGet]
        public IActionResult Create()
        {
            Customer customer = new Customer();
            return View(customer);
        }


        [HttpPost]
        public IActionResult Create(Customer customer)
        {
            _context.Attach(customer);
            _context.Entry(customer).State = EntityState.Added;
            _context.SaveChanges();
            return RedirectToAction("index");
        }
    }
}

BikeStoreSampleMvcEFCore.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BikeStoreSampleMvcEFCore.Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">BikeStore範例網站 ( MVC + EFCore) </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        @*<li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                            </li>*@
                        @*<li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Customer" asp-action="Index">Customer</a>
                            </li>*@
                        @*<li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                            </li>*@
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <div class="modal" tabindex="-1" id="form-modal">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title"></h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    
                </div>
             
            </div>
        </div>
    </div>



    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - BikeStoreSampleMvcEFCore.Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

BikeStoreSampleMvcEFCore.Web/Views/Shared/_Pager.cshtml
@model BikeStoreSampleMvcEFCore.Web.Models.Pager

<div class="container">
    @if (Model.TotalPages > 0)
    {
    <ul class="pagination justify-content-end">

        @if (Model.CurrentPage > 1)
        {
            <li class="page-item">
                <a class="page-link" asp-controller="Customer" asp-action="Index" asp-route-pg="1">首頁</a>
            </li>
            <li class="page-item">
                <a class="page-link" asp-controller="Customer" asp-action="Index"
                   asp-route-pg="@(Model.CurrentPage-1)">前一頁</a>
            </li>
        }
        @for (var pge = Model.StartPage; pge <= Model.EndPage; pge++)
        {
            <li class="page-item @(pge == Model.CurrentPage ? "active" : "")">
                <a class="page-link" asp-controller="Customer" asp-action="Index" asp-route-pg="@pge">@pge</a>
            </li>
        }
        @if (Model.CurrentPage < Model.TotalPages)
        {
            <li class="page-item">
                <a class="page-link" asp-controller="Customer" asp-action="Index"
                   asp-route-pg="@(Model.CurrentPage+1)">下一頁</a>
            </li>
            <li class="page-item">
                <a class="page-link" asp-controller="Customer" asp-action="Index"
                   asp-route-pg="@(Model.TotalPages)">最後頁</a>
            </li>
        }


    </ul>
    }




</div>